#!/bin/bash
# -----------------------------------------------------------------
# Notre script "snake", équivalent de "artisan" de Laravel.
#
# Il gère nos raccourcis (install, run, config-server)
# et passe tout le reste directement à manage.py
# (ex: "craft ...", "migrate", "createsuperuser")
# -----------------------------------------------------------------

# Le premier mot que tu tapes après "snake" (ex: "run")
COMMAND=$1

case "$COMMAND" in
    # ---------------------------------
    # NOS RACCOURCIS DE PROJET
    # ---------------------------------
    
    install)
        echo "--- Installation des dépendances depuis requirements.txt ---"
        pip install -r requirements.txt
        ;;

    run)
        echo "--- Lancement du serveur sur http://127.0.0.1:8000 ---"
        python3 manage.py runserver
        ;;

    config-server)
        echo "--- Configuration du serveur (automigrate) ---"
        python3 manage.py craft automigrate
        # python3 manage.py craft seed:all
        ;;

    help)
        echo "Commandes personnalisées de 'snake' :"
        echo "  \033[36minstall\033[0m        Installe les dépendances (requirements.txt)"
        echo "  \033[36mrun\033[0m            Lance le serveur de développement"
        echo "  \033[36mconfig-server\033[0m  Configure le serveur (automigrate)"
        echo ""
        echo "Toute autre commande (ex: 'craft ...', 'migrate', 'createsuperuser') est passée à manage.py."
        ;;
    seed:all)
        echo "--- Lancement de tous les seeders (Ordre : Access -> Roles) ---"
        python3 manage.py seed_access
        python3 manage.py seed_navigation
        python3 manage.py seed_roles
        
        echo "--- Tous les seeders sont terminés ---"
        ;;

    # ---------------------------------
    # COMMANDE PAR DÉFAUT
    # ---------------------------------
    *)
        # Si la commande n'est pas connue, on la passe à manage.py
        # Cela inclut TOUTES les commandes "craft"
        python3 manage.py "$@"
        ;;
esac