# Generated by Django 5.2.7 on 2025-11-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('display_mod', models.CharField(default='list-view', help_text='ex: card-view, list-view', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: pascal-icon-dashboard)", max_length=100)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom (ex: Lire les examens)')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename (ex: view_examen)')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag (ex: examen)')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['tag', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: client-icon)", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('link', models.CharField(help_text='Lien React (ex: /clients)', max_length=255)),
                ('permission_tags', models.JSONField(blank=True, default=list, help_text='Liste des tags de permission (ex: ["client"])')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.module')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='core.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
